### ISSUE TITLE
Support experimental versions

### ISSUE THREAD

**Issue by smashwilson** [rgbkrk/dvm#26]
It'd be cool to be able to install and flip between experimental versions, too. Installation instructions are [in the Docker repo](https://github.com/docker/docker/tree/master/experimental).

`dvm ls-remote` wouldn't pick these up, but maybe that's okay.

**Comment by rgbkrk** [comment]
I'm assuming there's only the *one* version of the experimental binary, at:

```
https://experimental.docker.com/builds/Linux/x86_64/docker-latest
```

Which means `ls-remote` could just list "experimental" I assume? I just checked and the Darwin, etc. paths are all there. I just don't see a way to switch to old versions.

**Comment by smashwilson** [comment]
Oh, that would make sense. I know the experimental binary is a nightly rather than a specific tag.

> Which means ls-remote could just list "experimental" I assume? I just checked and the Darwin, etc. paths are all there. I just don't see a way to switch to old versions.

:+1:

We should be able to special-case it in just like `system` is.

**Comment by rgbkrk** [comment]
I'm ok if we leave it in the listing by default. The only tricky bit is that we assume if one has been downloaded already to not download it again. We'd special case experimental then:

1. Grab the SHA256 sum
2. If we have an experimental binary on disk, compare with the SHA256 sum (if match, done)
3. Download the latest experimental binary

**Comment by rgbkrk** [comment]
Note from #27: I included experimental in ls-remote - hope that's cool.
