### ISSUE TITLE
.dvmrc

### ISSUE THREAD

**Issue by smashwilson** [rgbkrk/dvm#7]
Do we need to support a `.dvmrc`? I'm not sure if it has the same value for dvm as it does for nvm or rvm. You're most likely to need a Docker version shift when you're targetting different environments, not when you're changing projects.

We should either support it like the others, or remove references to it from the help text.

**Comment by rgbkrk** [comment]
The only thing that I think makes sense is watching for a (yet unnamed) variable called `DOCKER_VERSION`.

```bash
$ source docker.env # assuming it sets DOCKER_VERSION to e.g. 1.8.2
$ dvm install # implicit arg
```

**Comment by rgbkrk** [comment]
Seems like we're going with `DOCKER_VERSION`.
